### ISSUE TITLE
flixel.addons.editors.tiled.Layer does not initialize member "tiles"

### ISSUE THREAD

**Issue by robo-hamburger** [HaxeFlixel/flixel-addons#120]
tileArray seems trigger initializing it which is rather confusing since it is a property. Better behavior would be for both of them to be initialized in the constructor or both as properties that lazily decode things like tileArray does now.

**Comment by Gama11** [comment]
This seems to have been resolved since: https://github.com/HaxeFlixel/flixel-addons/blob/56d49c13f51fbe9b94eff2bd2758478fb1d17c54/flixel/addons/editors/tiled/TiledTileLayer.hx#L33
