### ISSUE TITLE
HTML5 target compilation errors when including flixel-addons in basic hello world

### ISSUE THREAD

**Issue by AdamHarte** [HaxeFlixel/flixel-addons#143]
Create a basic project using:
> `flixel tpl -n "HelloWorld"`

Then uncomment the haxelib flixel-addons from the Project.xml so it is included in the game.
> `<haxelib name="flixel-addons" />`

When running the game for Flash target everything is fine, but if run for HTML5 target, there are errors. If the flixel-addons haxelib is not included, then the game runs for both flash and html5 targets without any trouble.

Using:
> Windows 8
Haxe 3.1.3
flixel 3.3.6
flixel-tools 1.0.2
flixel-addons 1.0.3
flixel-templates 1.0.2
openfl 2.1.7

I have the full output log at this gist: https://gist.github.com/AdamHarte/d9131c747eab3b29b43d

**Comment by Gama11** [comment]
That looks like some bitfive / openfl incompatiblity. Flixel doesn't use bitfive by default anymore on dev. On the latest release, you can try `-D no-custom-backend`.
