### ISSUE TITLE
backgroundcolor property from Tiled maps

### ISSUE THREAD

**Issue by pabab** [HaxeFlixel/flixel-addons#147]
It would be usefull to read the backgroundcolor map property from Tiled tilemaps and make it available. This could be achieved adding to TiledMap.hx something like the following code:

```haxe
public var backgroundColor: Int;
```

```haxe
var bgColorStr = source.att.backgroundcolor;
if (bgColorStr != null) 
{
	bgColorStr = StringTools.replace(bgColorStr.toUpperCase(), "#", "0x");
	backgroundColor = Std.parseInt(bgColorStr);
}
else
{
	backgroundColor = 0;
}
```

Unfortunately, when testing this code, parsing the color integer from the hexadecimal value doesn't seem to give the correct results.

**Comment by Beeblerox** [comment]
@pabab your snippet will work if you change the type of `backgroundColor` var from `Int` to `FlxColor` and replace the line:
```
backgroundColor = Std.parseInt(bgColorStr);
```
with the following line:
```
backgroundColor = FlxColor.fromString(bgColorStr);
```
