### ISSUE TITLE
FlxSpriteAniRot sprite animation shows rotation frames, not animation frames; angle property shows normal rotation, not baked rotation

### ISSUE THREAD

**Issue by mai-ichii-tkb** [HaxeFlixel/flixel-addons#148]
I'm having difficulty in making FlxSpriteAniRot work properly. 

With the code below I was able to display the sprite, but it's not animating as expected. What looks to be happening is it's going through the rotation frames instead of the other frames of the animation. Also, setting its angle = <something> triggers the normal rotation of FlxSprite, and not the baked rotations I would have expected. 

swordSlash = new FlxSpriteAniRot("assets/images/effects/slashAmini.png", 8);
swordSlash.animation.add("slashA", [0, 1, 2, 3, 4], 5, false);
swordSlash.animation.play("slashA");

But maybe this is improper use of FlxSpriteAniRot? If so, can someone point me in the correct direction?

**Comment by Gama11** [comment]
I don't think there's enough details here to reproduce the problem (only an incomplete code snippet and it needs an asset).
