### ISSUE TITLE
In FlxNapeSprite:addPremadeBody()

### ISSUE THREAD

**Issue by xerosugar** [HaxeFlixel/flixel-addons#151]
If body is null and space haven't yet been set, this line will crash the program:
https://github.com/HaxeFlixel/flixel-addons/blob/dev/flixel/addons/nape/FlxNapeSprite.hx#L142

Maybe just change it to? -> NewBody.space = FlxNapeState.space;
Or change the method signature, letting the user provide a preferred space? -> addPremadeBody(NewBody:Body, ?_space:Space)

Edit: Btw, this happens when 'CreateRectangularBody' is set to false in the constructor.

**Comment by Gama11** [comment]
Please always provide a reproducible code example in bug reports if possible. From your description it sounds like something like this would reproduce the error:

```haxe
var sprite = new FlxNapeSprite(0, 0, null, false);
sprite.addPremadeBody(new Body(BodyType.DYNAMIC, new Vec2(0, 0)));
```

(without a `FlxNapeSpace.init() call`)

which it doesn't. What am I missing?

**Comment by xerosugar** [comment]
When I tried it a couple of minutes ago, it didn't crash, but the sprite's physics body wasn't there when I looked at the debug graphics. Did you check that as well? I'll try to provide code for issues in the future.

**Comment by Gama11** [comment]
Yeah, but that's expected because the body I created in my snippet doesn't have a shape associated with it.

```haxe
FlxNapeSpace.init();
var sprite = new FlxNapeSprite(100, 100, null, false);
var body = new Body(BodyType.STATIC, new Vec2(0, 0));
body.shapes.add(new Polygon(Polygon.box(50, 50)));
sprite.addPremadeBody(body);
add(sprite);
```

You also need to set `physicsEnabled` to true explicitly.

**Comment by xerosugar** [comment]
A small misunderstanding here I think :) I meant that, when I called addPremadeBody(bodyWithShapes) while having createRectangularBody = false, I was expecting it to work, since the comment for that parameter says "Whether to create a rectangular body for this sprite (use false if you want to add a custom body)." The code, with my change, feels more logical since you've made it clear in two places already 1) do not create a rectangularbody, and 2) addPremadeBody() that you, the user, want to use a custom-made Body for this sprite. What do you say?

**Comment by Gama11** [comment]
Well, you did originally describe a bug / crash here, but instead it's unexpected behavior (`physicsEnabled` not being set to true)?

**Comment by Gama11** [comment]
I'm thinking your real issue might be that the `EnablePhysics` argument is ignored if `CreateRectangularBody` is false in the constructor?

**Comment by Gama11** [comment]
I think we could simply lift the restriction of `EnablePhyiscs` being ignored in that case (the behavior of that parameter is documented I guess, but perhaps not super intuitive).

**Comment by xerosugar** [comment]
if you think about it, how often do you create a Body that you do not wish to use in the physics simulation? wouldn't you just remove it from the Space altogether if you didn't want it? what's the benefit of removing it from the Space compared to setting physicsEnabled to false?
what if physicsEnabled was true by default and - in a similar manner to the 'immovable' flag - had to be set to your value of choice explicitly if you wanted to change it later? I think the latter feels more intuitive tbh
