### ISSUE TITLE
Add a "TiledImage.hx" to the Tiled library

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel-addons#155]
Similar to this: 
https://github.com/kasoki/openfl-tiled-flixel/search?utf8=%E2%9C%93&q=ImageLayer&type=Code
https://github.com/kasoki/openfl-tiled/blob/fc82b84c7c49a5ec80a86cc5c62566542a8deb14/openfl/tiled/ImageLayer.hx

Right now (I think) the flixel-addons Tiled classes do not support Tiled's image layers, though such support can be very useful (for example, you can use Tiled as a non-tiles level editor).

**Comment by Beeblerox** [comment]
@sruloart can you provide sample Tiled project with image in it? So it would be easier to work on this issue (since I don't have experience with Tiled)

**Comment by sruloart** [comment]
[Sure!](http://www.filedropper.com/tilededitor-imagelayer)
It's the same basic Tiled demo (latest dev version) only with an added image layer on the .tmx map file.
