### ISSUE TITLE
Multiple Problems with Tiled Map

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel-addons#170]
I'm trying to get it to work, and I'm running into problems that I can't figure out:

First: it would be helpful to have some kind of examples or demos or code showing how to use the Tiled maps, preferably from the author. I have no idea how it's supposed to be used...

In the only sample code I found, it's using `TiledMap.getLayer()`, however, this throws an error for me, because `layerMap` is never initialized and never set to anything. I came up with some code to build `layerMap` (although I'm not positive it's right), but then get a bunch of errors when I try using `get_csvData` or `get_tileArray` `data is missing attribute encoding`.

**Comment by Gama11** [comment]
I guess this was fixed by #172.
