### ISSUE TITLE
StageSizeScaleMode doesn't work with TiledMap

### ISSUE THREAD

**Issue by Mixerman123** [HaxeFlixel/flixel-addons#175]
If the current scale mode is set to StageSizeScaleMode, if you stretch the window while a TiledLevel is shown in a substate, you can see behind the substate into whatever view is there. For some reason, sometimes when you stretch it, it covers the full window, but most of the time it leaves a gap. It works fine with all other scale modes.

Also, when you work around in a tiled level, it normally only shows whats on the the screen and hides the other tiles. I can visibly see it adding the tiles on as I walk around the area.

Image: http://i.gyazo.com/79374bb213832845e1ecff9ed3534b38.png (Left is a map, right is my other view)

**Comment by Gama11** [comment]
You might need to call `updateBuffers()` on the tilemap whenever a resize happens.

If that doesn't help, could you provide some code to reproduce the issue?

**Comment by Mixerman123** [comment]
Yep, it works, thanks very much :+1:
