### ISSUE TITLE
TiledMap and Map Properties

### ISSUE THREAD

**Issue by nospoone** [HaxeFlixel/flixel-addons#178]
Having custom map properties on a `.tmx` file makes TiledMap crash. I'm using dev for both `flixel` and `flixel-addons`.

Here's a [project showing the issue](http://files.q-bit.ca/hf-fa-tiledcrash.zip), I've included a `.tmx` that works and one that does not.

**Comment by gitfib** [comment]
i've also encountered this. fix: https://github.com/HaxeFlixel/flixel-addons/pull/183
