### ISSUE TITLE
To use state transitions do I necessarily have to inherit from FlxTransitionableState?

### ISSUE THREAD

**Issue by guifes** [HaxeFlixel/flixel-addons#182]
If so, does that mean I can't have a FlxUIState that's also a FlxTransitionableState?

**Comment by Gama11** [comment]
Yes and no. `FlxUIState` has a [pretty nasty hack](https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/FlxUIState.hx#L31-L35) in place that makes sure it extends `FlxTransitionableState` if flixel-addons is included.
