### ISSUE TITLE
FlxTilemapExt more Extended

### ISSUE THREAD

**Issue by adrianulima** [HaxeFlixel/flixel-addons#188]
Hi, I'm new with HaxeFlixel and with Git repositories. Last year I used HaxeFlixel in some tests, but since then I haven't used it. This year I worked just with `AS3`, `Objective C` and `Swift`.
Now I decided back to `Haxe` learning and, if I can, contribute with the community.

![FlxTilemapExt](https://cloud.githubusercontent.com/assets/13324869/9938958/1585dbde-5d3e-11e5-8a0f-ffe303c7a341.gif)

Last year I made some modifications to `FlxTilemapExt` to allow player down in cloud tiles. I also added two more levels of slopes, **67.5** and **22.5** degrees.
As were my first code with HaxeFlixel, they are not optimized and are not compatible with the version **4.0.0**.

![Slopes Example](https://41.media.tumblr.com/85d5641f578b5f41a65c5a8470130ff9/tumblr_nfuxw3MAA11u4s9q0o2_400.png)
*My [Twitter](https://twitter.com/adrianulima) has more images.*

##### So, could I try rewrite this modifications as improvements to this repository?
- ~~Possibility to walk through slope tiles~~
- [x] Possibility to player fall in cloud tiles
- [x] 67.5° Slopes floor and ceiling
- [x] 22.5° Slopes floor and ceiling
- [x] Jump walls
- [x] Reversal of gravity

**Comment by Beeblerox** [comment]
@adrianulima that would be awesome!

**Comment by larsiusprime** [comment]
:+1: :+1: :+1:

**Comment by adrianulima** [comment]
@Beeblerox  @larsiusprime I made the modification to have conditional tiles.
I installed the desktop github  and did commit to dev branch in flixel-addons, is it right? I have to do something more to you can see it?

I also have a modified version of the demo to commit, when I do the right thing here I'll do there to... xD

**Comment by larsiusprime** [comment]
@adrianulima The steps are these:

1) Fork flixel-addons if you haven't already
2) Push your changes to *your fork* of flixel-addons, to the dev branch
3) On github, go to your fork of flixel-addons, and open a pull request to the main repository

**Comment by adrianulima** [comment]
@larsiusprime thanks for spell out.
I did it, but I have to study Haxe a little more before try pull-request something big.
https://github.com/HaxeFlixel/flixel-addons/pull/189

I'm still learning the structure of HaxeFlixel, and meanwhile doing some cool stuff.
![wall_jump](https://cloud.githubusercontent.com/assets/13324869/9998267/bed6b94e-6066-11e5-9b67-99dcff70ff2e.gif)

If I can contribute with codes in some way, I would love to be helpful.
As @Gama11 said, I could contribute with this type of demo to the haxeflixel mechanics site.

Can I close this issue? or I may try to end the slopes modification?

**Comment by Gama11** [comment]
More slope degrees sounds like a useful addition to me.

Also, the walljumping in that .gif looks quite cool. Not sure if we have a demo with walljumping yet, I don't think so though... ;)
