### ISSUE TITLE
Do TiledLayers need cast()?

### ISSUE THREAD

**Issue by leoncvlt** [HaxeFlixel/flixel-addons#196]
I recently switched to the dev branch, before I would load a tiled map / objects with
```
var coinsLayer:TiledObjectLayer = tiledMap.getObjectGroup("coins");
for (i in coinsLayer.objects) {
...
```

Now I saw that TiledMap stores the layers in a single array, however if I do
`var coinsLayer:TiledObjectLayer = tiledMap.getLayer("coins")` it complains about not being the right class (it needs a `TiledObjectLayer` if I want to access `objects`, while `getLayer` returns the base class `TiledLayer`).

It work if I cast the layer like this:
```
var coinsLayer:TiledObjectLayer = cast(tiledMap.getLayer("coins"), TiledObjectLayer);
for (i in coinsLayer.objects) {
...
```

Is there a simple / cleaner way to do this or is this the correct workflow for using Tiled files now? It seems like a step down in straightforward-ness from the other approach.

**Comment by Gama11** [comment]
This changed with the Tiled refactor in #162. Any thoughts @JoeCreates?

**Comment by JoeCreates** [comment]
A static cast would be best here I think, I.e cast layers.get("coins"), no
brackets on the cast. Not that it's going to make much difference.

By the way, the reason for the change is that the single array now means
that the order of object and tile layers is now kept, whereas before object
and tiled layers were separated, losing the order they were in the editor.
If, before, you were always using a set number of object layers and always
in the same place relative to the tile layers, you now have the option of
creating tile maps or flxgroups in the order they are in the editor. This
way you may be able to implement a more flexible way of loading maps where
you do not need to refer to specific layers.

For example, I loop over every layer in the array, then check if it's
either a tile or object layer to do the appropriate thing with it,
ultimately adding either a tile map or a flxgroup to my main world
flxgroup. When loading an object layer, you could check its name or a
custom property to determine that it is a coin layer.

**Comment by Gama11** [comment]
I guess the only way to avoid casting is to maintain a separate `Map` and getter function for each layer type. Might not even necessarily be a bad idea, having to cast isn't very desirable...

Thoughts?

**Comment by gamedevsam** [comment]
Alternatively we could have a function called ```getObjectLayer``` that did the cast implicitly.

**Comment by JoeCreates** [comment]
I don't see that that would be any better than just using the static cast. It's actually fewer characters and would avoid bloating the api:

```
var coinsLayer:TiledObjectLayer = cast tiledMap.getLayer("coins");
var coinsLayer:TiledObjectLayer = tiledMap.getObjectLayer("coins");
```

Of course the latter way would make it possible to imply the type, but I don't think it would be worth it.
