### ISSUE TITLE
TextFormat on FlxTypeText

### ISSUE THREAD

**Issue by pizzamakesgames** [HaxeFlixel/flixel-addons#199]
Would love to be able to change the line spacing / leading via TextFormat on text displayed with FlxTypeText. It does work with FlxText already, so I'd hope it wouldn't be too hard to make it work with FlxTypeText as well?

**Comment by Gama11** [comment]
Did you figure out how to do this?

**Comment by pizzamakesgames** [comment]
I'm afraid not. I only figured out how to change the .ttf's line spacing beforehand. The functionality of using TextFormat was highly inconsistent on the different targets, so a way to change the line spacing on FlxText or FlxTypeText without the use of TextFormat would be the thing to desire here, I think, rendering this issue obscure.
