### ISSUE TITLE
TiledMap does not parse csv correctly.

### ISSUE THREAD

**Issue by MintPaw** [HaxeFlixel/flixel-addons#209]
TiledMap parses an extra tile of width when using loadMapFromCSV
Example load:
<code>_tilemap.loadMapFromCSV(cast(tiledMap.layers[0], TiledTileLayer).csvData, ...);</code>

The problem is that Tiled csv looks like this: http://pastebin.com/MeTu0eYN
And Flixel CSV is expected to look like this: http://pastebin.com/vezbBnwk
Note the extra comma on the end of each tile row from line 8 to line 28.

This causes FlxTilemap to load an extra tile there with value 0. Changing the tilemap to the expected format fixes the problem, although obviously the map fails to load in the Tiled editor.

It's a hard bug to spot, I noticed it when setting my camera scroll bounds, they have to be:
<code>
FlxG.camera.setScrollBoundsRect(0, 0, _tilemap.width - tileWidth, _tilemap.height, true);
</code>

**Comment by Gama11** [comment]
Same issue as HaxeFlixel/flixel#1520.
