### ISSUE TITLE
FlxTilemapExt : Cannot load Level from static variable

### ISSUE THREAD

**Issue by Blist** [HaxeFlixel/flixel-addons#211]
In the FlipRotationAnimationTiles, if I load a level into a static member and add it on a FlxState, nothing is happening , no sprite displays and no error on the console. But if i load the level on a member of my FlxState, I can see my level.

this not work.
```haxe
level = MapManager.level;
add(level.backgroundGroup);
add(level.foregroundGroup);
add(level.collisionGroup);
super.create();
```

this work.
```haxe
level = new Level("mymap","myanim");
add(level.backgroundGroup);
add(level.foregroundGroup);
add(level.collisionGroup);
super.create();
```

**Comment by Gama11** [comment]
That's not enough code to reproduce to reproduce the issue. When and how are you initializing the static variable?

If you're on the flash target, are you using the debug flash player to see exceptions?

**Comment by Blist** [comment]
Hi,
This is a source code to reproduce this issue. I use the FlipAnimationTiled demo.
http://code.vikindie.fr/Vianney/BugOnFlixelAddons/tree/master/source
I build with the neko target.

I hope it can help you

**Comment by Gama11** [comment]
That page requires a login.

**Comment by Blist** [comment]
Sorry, mistake on the url
http://code.vikindie.fr/Vianney/IssueOnFlixelAddons/tree/master/source

**Comment by Gama11** [comment]
Flixel caches graphics of tilemaps and sprites and destroys them on state switches. In the static case, they are created before `PlayState` exists, so they get destroyed during the switch to it.

Either avoid creating sprites / tilemaps outside of the state they are used in, or make sure you set `.graphic.persist = true` for all of them (or flip `FlxGraphic.defaultPersist`).

**Comment by Blist** [comment]
oh ... i dont no the cache system of flixel, now I understand my problem, thank a lot :)
