### ISSUE TITLE
FlxTypedText.addFormat apply new format to all string.

### ISSUE THREAD

**Issue by n06rin** [HaxeFlixel/flixel-addons#214]
I want change color for several symbols.
For example at create () of MenuState we adding:

```haxe
text = new FlxTypeText(15, 10, FlxG.width - 30, "start", 8, true);
text.addFormat(new FlxTextFormat(0x0080FF, false, false, 0xFFFFFF), 6, 11);
text.resetText("lorem ipsum!!!1111111111111111111111");
add (text);
text.start(0.01, false, false); 
```
At flash we see everything is ok:
![screenshot of flash](http://i.imgur.com/nEazVpy.png)

But at html5:
![screenshot of html5](http://i.imgur.com/8lQIukW.png)

**Comment by Gama11** [comment]
`FlxText`'s `FlxTextFormat` depends on `flash.text.TextFormat`, and OpenFL doesn't support that right now for HTML5 / OpenFL Next, see openfl/openfl#905
