### ISSUE TITLE
Error handling wanted here (FlxNapeTilemap)

### ISSUE THREAD

**Issue by xerosugar** [HaxeFlixel/flixel-addons#233]
https://github.com/HaxeFlixel/flixel-addons/blob/dev/flixel/addons/nape/FlxNapeTilemap.hx#L104

If 'getTileCoords' cannot find the specified index, 'coords' will be null and the game will crash.
a simple 'if (coords == null) continue;' or similar should be enough.

**Comment by Gama11** [comment]
I wonder what the best behavior there is. Wouldn't you want to know if the point is outside the map bounds?

**Comment by xerosugar** [comment]
I think in this case it'd be best to let the user decide if it's a problem or not.
As an example: If I'm implementing screen wrapping (exit from right, enter from left) and want to just be able to change the characters x position without being afraid that the Body is falling off the stage when it exits the screen, I want to be able to maybe add some "padding" and would in that case not benefit from that kind of error handling you speak of.

**Comment by Gama11** [comment]
Yeah.. either way it's probably better not to crash here. PR?

**Comment by xerosugar** [comment]
alright, I just have to remember how to do that :) making dinner atm, but I'll get on it asap.
