### ISSUE TITLE
Nape debug sprite does not scale with window size

### ISSUE THREAD

**Issue by owyoow** [HaxeFlixel/flixel-addons#242]
I'm testing my game on a smaller resolution than the design resolution and when I turn on the nape debug draw, the debug sprites do not scale with the window. There are design resolution size and offset from the sprites they belong to.

I fixed this by multiplying the debug sprite scale and position by the scaleMode scale but I'm not sure if this is the right way to do it.

I changed it in the `draw()` function in `FlxNapeSpace.hx` from:

```
sprite.scaleX = zoom;
sprite.scaleY = zoom;

sprite.x = -FlxG.camera.scroll.x * zoom;
sprite.y = -FlxG.camera.scroll.y * zoom;
```

to:

```
sprite.scaleX = zoom * FlxG.scaleMode.scale.x;
sprite.scaleY = zoom * FlxG.scaleMode.scale.y;

sprite.x = -FlxG.camera.scroll.x * zoom * FlxG.scaleMode.scale.x;
sprite.y = -FlxG.camera.scroll.y * zoom * FlxG.scaleMode.scale.y;
```

**Comment by Gama11** [comment]
Hm, I wonder when this broke.

**Comment by Gama11** [comment]
Looks like I fixed this in https://github.com/HaxeFlixel/flixel-addons/commit/00b2b3710085be7b983ad45ec4886f27432de61b#diff-8de124c7f2fe354b5c25e9d10a89af2a but forgot to close this issue.
