### ISSUE TITLE
optionally block Input in FlxText and so on

### ISSUE THREAD

**Issue by buckle2000** [HaxeFlixel/flixel-addons#252]
currently, if you use `FlxG.keys.pressed.*` to check input, even if you are typing, other `FlxObject` will receive key input.
for example, if I pressed `left` in `FlxInputText`, a sprite behind it will also move.
I think it is convenient to have a `blockInput` property to all keyboard-enabled ui element, when enabled, will set `FlxG.keys.pressed.*` and `-justPressed` to false after they receive these input.

**Comment by Gama11** [comment]
Wrong repo (`FlxInputText` is in flixel-ui).
