### ISSUE TITLE
HaxeFlixel loop nolonger accepts inputs while using FlxSpine in the HTML5 target.

### ISSUE THREAD

**Issue by troyedwardsjr** [HaxeFlixel/flixel-addons#262]
The HaxeFlixel update loop no longer accepts inputs from if/else statements when using FlxSpine in the HTML5 target, demo or otherwise. This only happens when you unfocus once, but it happens permanently then after whether you unfocus or refocus. This happens whether or not FlxG.autopause is set to true or false.

Not sure if this is a FlxSpine or SpineHaxe issue. 

Using flixel 4.1.1, flixel-addons 2.1.0, lime 2.9.1 and openfl 3.6.1

**Comment by Gama11** [comment]
Seems to be working fine now with OpenFL 8 (in the FlxSpine demo).
