### ISSUE TITLE
FlxSliceSprite slicing issues

### ISSUE THREAD

**Issue by Eiyeron** [HaxeFlixel/flixel-addons#275]
Hi. Trying to use this class, I got to see a curious issue while using the last dev of flixel-addons (to have the sprite fix), there is an issue with the rightmost and bottom borders: they do not appear at all

``` haxe
//...
        background = new FlxSliceSprite(AssetPaths.textbox_slice__png, new FlxRect(6,8,32,32), 320, 16+NUM_LINES*21); // NUM_LINES = 3
        add(background);
//...
```

Here's an example of what it looks like (the right window is a neko build, which works). I don't have a clue on why it doesn't work, sadly.

![2016-10-12-234656_1338x546_scrot](https://cloud.githubusercontent.com/assets/936086/19328996/d3a32082-90d6-11e6-9cf3-7e75c1829a50.png)

Here's the used 9slice sprite
![textbox_slice](https://cloud.githubusercontent.com/assets/936086/19329082/436f8ba8-90d7-11e6-9f2c-e9951ad8bda6.png)

Have a nice day and thanks for your hard work!

Edit : After trying on Flash, I also got to see that using the exact same parameters, I get also an erroneous result on this target on the right side : two extra pixel columns are shown.
![screenshot_2016-10-14_14-29-30](https://cloud.githubusercontent.com/assets/936086/19387495/dcee9b72-921a-11e6-9beb-b63293dcfbd7.png)

**Comment by Geokureli** [comment]
I'm having issues similar with FlxSliceSprite when playing on Safari.
<img width="620" alt="Screen Shot 2019-07-01 at 4 46 51 PM" src="https://user-images.githubusercontent.com/2609513/60469203-86be8f00-9c21-11e9-8aa8-8eb87057483e.png">
Compare the above with the result on Chrome
<img width="623" alt="Screen Shot 2019-07-01 at 4 57 50 PM" src="https://user-images.githubusercontent.com/2609513/60469237-a2c23080-9c21-11e9-91d4-76b9e1fa46a2.png">
Note that in this example the height of the sprite matches the source height, while the width is 1 greater

**Comment by Beeblerox** [comment]
@Geokureli can you provide a texture you're using for slicing and having problem with?

**Comment by Geokureli** [comment]
sure can
![UiPellet](https://user-images.githubusercontent.com/2609513/60517956-2b82b000-9ca6-11e9-8a9b-a6c66b3aa561.png) ![UiPellet_filled](https://user-images.githubusercontent.com/2609513/60517968-30476400-9ca6-11e9-8acb-a10721d793e1.png)
the rect is `FlxRect.get(2, 2, 1, 1)`

**Comment by Beeblerox** [comment]
I guess that's because of the size of the texture (not the power of two).
What happens if you set `openfl_power_of_two` in your project.xml? 
Just try to add 
`<haxedef name="openfl_power_of_two" />` 
line before 
`<haxedef name="openfl_power_of_two" />`

**Comment by Geokureli** [comment]
this works, why does this matter on safari?

**Comment by Beeblerox** [comment]
Safari is kind of a special (uses its own WebGL implementation) :)
I must warn you that using `openfl_power_of_two` flag increases memory usage (because all non-power-of-two-textures are being increased in size).
i'll try to improve sliced sprite class a bit, so you'll need to change only textures of those problematic sprites.

**Comment by Beeblerox** [comment]
@Geokureli and this problem may also be the case for FlxBackdrop and FlxTiledSprite as well

**Comment by Geokureli** [comment]
I resized the graphic to be 8x8 instead of 6x6 by adding alpha to the bottom right. Now only the topleft shows unless `openfl_power_of_two` is enabl.ed
<img width="519" alt="Screen Shot 2019-07-11 at 2 37 14 PM" src="https://user-images.githubusercontent.com/2609513/61080032-c471a380-a3e9-11e9-9c79-f8b1badfcad8.png">

**Comment by Beeblerox** [comment]
@Geokureli hello! 
Sorry for not anwering earlier.
i've made some changes for `FlxSliceSprite` and created PR: https://github.com/HaxeFlixel/flixel-addons/pull/334

With this change you could define which part of the source image to use. So for your case, when you change size of the graphic to 8x8 pixels, you could use it like this:
```
var sliceSprite1:FlxSliceSprite = new FlxSliceSprite("assets/slice_1.png", FlxRect.get(2, 2, 1, 1), 200, 25, FlxRect.get(0, 0, 6, 6));
```
(as you can see i've added optional constructor argument called `SourceRect`)

**Comment by Geokureli** [comment]
Sorry for the late response, #344 seems like a good change to make.

Unfortunately, I'm not really sure how this helps me. currently the only way to (kinda) fix my Safari issue is by enabling `openfl_power_of_two`.

I'm still pretty confused on what `openfl_power_of_two` does. here's a list of results I'm seeing:
### openfl_power_of_two(Po2) enabled
Regardless of whether the image is 6x6 or 8x8, regardless of whether I use the new sourceRect and regardless of the browser, the pellets look like this:
<img width="134" alt="Screen Shot 2019-07-15 at 6 28 43 PM" src="https://user-images.githubusercontent.com/2609513/61255587-d1b2c900-a72e-11e9-892b-87de0bf7ea14.png">
Notice the bottom and right pixels are slightly thinner than the opposing sides. (compare with below)

### Chrome with Po2 is disabled
With a 6x6 image, or with an 8x8 image when I use sourceRect it looks correct
<img width="123" alt="Screen Shot 2019-07-15 at 7 07 43 PM" src="https://user-images.githubusercontent.com/2609513/61256827-db8afb00-a733-11e9-8296-e3e7fc0f87a5.png">
With an 8x8 image, without sourceRect it looks wrong in expected ways
<img width="121" alt="Screen Shot 2019-07-15 at 7 04 38 PM" src="https://user-images.githubusercontent.com/2609513/61256865-0f662080-a734-11e9-94f9-d7b39047bec1.png">


### Safari with Po2 is disabled
With a 6x6 image, or with an 8x8 image when I use sourceRect it looks like this:
<img width="141" alt="Screen Shot 2019-07-15 at 7 12 05 PM" src="https://user-images.githubusercontent.com/2609513/61257091-193c5380-a735-11e9-813a-571259c1de9c.png">
8x8 with no sourceRect it looks like this:
<img width="139" alt="Screen Shot 2019-07-15 at 7 13 58 PM" src="https://user-images.githubusercontent.com/2609513/61257100-26594280-a735-11e9-8350-20151262ef29.png">

My best option is to use `openfl_power_of_two`, and then no matter what it will look wrong, even with the new additions.

**Comment by Beeblerox** [comment]
it seems i'm missing something with this fix. I'll try to run tests on Safari tonight after work and see how it behaves there.
The only thing that `openfl_power_of_two` does is that it grows textures sizes to nearest Po2 size and corrects UV coordinates that user (and Flixel) passes in for `drawTriangles` calls.

**Comment by Beeblerox** [comment]
@Geokureli can you say what size (width/height) you're setting for `FlxSliceSprite`s? (Maybe it handles some sizes incorrectly)

**Comment by Geokureli** [comment]
here's the entire class
```haxe
@:forward
abstract Pellet(FlxSliceSprite) to FlxSliceSprite
{
	inline static var SIZE = 6;
	static public var rect = FlxRect.get(2, 2, 1, 1);
	static public var sourceRect = FlxRect.get(0, 0, SIZE, SIZE);
	
	inline public function new (x = 0, y = 0, width = SIZE)
	{
		this = new FlxSliceSprite
			( "assets/images/ui/UiPellet.png"
			, rect
			, width
			, SIZE
			, sourceRect
			);
		this.stretchCenter = true;
		reset(x, y, width);
	}
	
	inline public function reset(x = 0.0, y = 0.0, width = SIZE):Void
	{
		this.loadGraphic("assets/images/ui/UiPellet.png");
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = SIZE;
	}
	
	inline public function highlight():Void
	{
		this.loadGraphic("assets/images/ui/UiPellet_filled.png");
	}
}
```
the instances are recycled , if that matters

**Comment by Beeblerox** [comment]
@Geokureli and `width` is always equal to `SIZE`?

**Comment by Geokureli** [comment]
no width is always 6 or greater

**Comment by Beeblerox** [comment]
i've checked FlxSliceSprite behavior on quite old Mac and van confirm that there is stil a problem (even in google chrome).
there is something with texture (size or filtering) - there is warning message in developer's console

i'll continue my work on fixing this

**Comment by Geokureli** [comment]
Is there anything I can do to help? Not much info is available on openfl_power_of_two and this safari issue when I search. Regardless, thanks for looking into this!

**Comment by Beeblerox** [comment]
@Geokureli sorry for long silence, but i think i finally know where is the problem with this class - it is in my pretty dumb implementation of slicing for tile render mode :)
i'll need to rewrite this class and it will take couple of evenings (i believe), so expect new fix this week

**Comment by Geokureli** [comment]
That's awesome! looking forward to it

**Comment by Beeblerox** [comment]
@Geokureli here is updated class: https://gist.github.com/Beeblerox/720c5b7b33571f7d7c2c7603b6aed062
i haven't tested it on Safari yet (will do it tomorrow at work), but i hope that it will work

**Comment by Beeblerox** [comment]
@Geokureli i've checked it on Safari and it seems to be working as expected (but you still have to use `SourceRect` and prepare slicel texture to be of power of 2 size)

**Comment by Beeblerox** [comment]
and here is related Pull Request: https://github.com/HaxeFlixel/flixel-addons/pull/335

**Comment by Beeblerox** [comment]
@Geokureli Have you tried it? did it help
