### ISSUE TITLE
Color property of FlxBackdrop has no effect

### ISSUE THREAD

**Issue by starry-abyss** [HaxeFlixel/flixel-addons#277]
Here is my simple project:
https://www.dropbox.com/s/osmdxcytyqkusfh/ld36-warmup.zip?dl=0

This line is crucial:

```
bg1.color = FlxColor.RED;
```

On Flash it's like this (good):
[red](http://i.imgur.com/CAigvzw.png)

While on neko (bad):
[blue](http://i.imgur.com/jrZyyuR.png)

Looks like it's not a regression, tested with older 4.x releases.

**Comment by Beeblerox** [comment]
actually there is no logic on native target to check whether is backdrop is tinted or not. will fix it tonight
