### ISSUE TITLE
Issue with loading Ogmo Tilemap

### ISSUE THREAD

**Issue by ryanisaacg** [HaxeFlixel/flixel-addons#278]
When I tried to load a tilemap, I got this error:

      project is missing attribute width
      Called from C:\HaxeToolkit\haxe\std/haxe/xml/Fast.hx line 56
      Called from flixel/addons/editors/ogmo/FlxOgmoLoader.hx line 48
      Called from flixel/addons/editors/ogmo/FlxOgmoLoader.hx line 10
      Called from PlayState.hx line 25
      Called from flixel/FlxGame.hx line 649
      Called from flixel/FlxGame.hx line 739
      Called from flixel/FlxGame.hx line 689
      Called from flixel/FlxGame.hx line 554
      Called from openfl/_legacy/events/EventDispatcher.hx line 98
      Called from openfl/_legacy/display/DisplayObject.hx line 182
      Called from openfl/_legacy/display/DisplayObject.hx line 161
      Called from openfl/_legacy/display/DisplayObjectContainer.hx line 286
      Called from openfl/_legacy/display/Stage.hx line 1103
      Called from openfl/_legacy/display/Stage.hx line 351
      Called from openfl/_legacy/display/Stage.hx line 1084
      Called from openfl/_legacy/display/Stage.hx line 430
      AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Gama11** [comment]
This is not enough information. Can you provide the map file so this can be reproduced?

**Comment by ryanisaacg** [comment]
I've attached the zip file with the level files from Ogmo.

[data.zip](https://github.com/HaxeFlixel/flixel-addons/files/573118/data.zip)

**Comment by Gama11** [comment]
I think you passed the wrong file to `FlxOgmoLoader` (the `oep` instead of the `oel`).

**Comment by ryanisaacg** [comment]
Yup, that was the issue. Thanks!
