### ISSUE TITLE
Upstream changes to spinehaxe breaks flixel-addons (and flixel).

### ISSUE THREAD

**Issue by seraku24** [HaxeFlixel/flixel-addons#281]
I noticed a Travis CI build break with @Beeblerox's recent commit (see HaxeFlixel/flixel@dcc66b34a3d437729cf2749cf56531f9817a0438) and decided to dig into the logs to see if I could spot the error.  The failure was within the FlxSpine addon/demo involving a reference to `spinehaxe.atlas.Texture`.  The file defining this interface was recently removed by @bendmorris when updating spinehaxe (see bendmorris/spinehaxe@390fcf264a9684918865606c724d694900af1b5c).  Since Travis was configured to pull the master branch of spinehaxe instead of a known-good branch, this resulted in the build break.

Upon further investigation, it appears that `spinehaxe.atlas.Texture` is a curious anomaly from the past.  `BitmapDataTextureLoader` (from spinehaxe) and `FlixelTextureLoader` (from flixel-addons) both added an extra method `loadTexture` that returns the type `Texture`, however this method was not part of the `spinehaxe.atlas.TextureLoader` interface.  It would seem this method never gets called, and there are no other references to the interface.

In spinehaxe, `BitmapDataTextureLoader` no longer has the `loadTexture` method.  The same change could be done with `FlixelTextureLoader` which should resolve the build break, providing that the method is indeed an irrelevant relic of yesteryear.

**Comment by Beeblerox** [comment]
@seraku24 thank you for reporting details!
i'll try to fix this stuff today

**Comment by bendmorris** [comment]
Sorry about that. Spine 3.2 had some breaking changes.

To avoid disrupting flixel in the future, I'll get spinehaxe onto haxelib so you can lock onto an explicit version. There was some confusion over the license requirements on haxelib (https://groups.google.com/forum/#!topic/haxelang/K3Rpl7N-vG4) that never really got resolved, but I'll figure something out.

**Comment by bendmorris** [comment]
Done, you can now install from haxelib if you want to avoid breaking changes: http://lib.haxe.org/p/spinehaxe

**Comment by Gama11** [comment]
The `spinehaxe.atlas.Texture` removal seems to be far from the only breaking change.

```
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/editors/spine/FlxSpine.hx:245: characters 31-41 : Float should be spinehaxe.Slot
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/editors/spine/FlxSpine.hx:245: characters 31-41 : For function argument 'slot'
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/editors/spine/FlxSpine.hx:308: characters 21-47 : spinehaxe.SlotData has no field additiveBlending
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/editors/spine/FlxSpine.hx:342: characters 20-46 : spinehaxe.SlotData has no field additiveBlending
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/editors/spine/FlxSpine.hx:359: characters 31-49 : spinehaxe.Bone has no field worldRotation (Suggestions: worldRotationX, worldRotationY)
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/editors/spine/FlxSpine.hx:669: characters 2-13 : spinehaxe.Skeleton has no field set_x
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/editors/spine/FlxSpine.hx:681: characters 2-13 : spinehaxe.Skeleton has no field set_y
source/SpineBoyTest.hx:28: characters 6-19 : spinehaxe.animation.TrackEntry has no field toString
source/SpineBoyTest.hx:31: characters 7-16 : spinehaxe.animation.TrackEntry has no field time
source/SpineBoyTest.hx:36: characters 7-16 : spinehaxe.animation.TrackEntry has no field time
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/editors/spine/FlxSpine.hx:667: lines 667-677 : Field set_x is declared 'override' but doesn't override any field
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/editors/spine/FlxSpine.hx:679: lines 679-689 : Field set_y is declared 'override' but doesn't override any field
```

@bendmorris The spinehaxe 3.5.0 release appears to already have all the breaking changes? So I guess that could only help in the future.

**Comment by Beeblerox** [comment]
@Gama11 yeah, i've seen these errors. and i'm working on fixing it.

**Comment by bendmorris** [comment]
>to avoid disrupting flixel in the future...

>I guess that could only help in the future.

Yep :) If it helps, I can put an older release up on haxelib so you can lock to that for now. If @Beeblerox will have this fixed soon, I won't worry about it.

**Comment by Beeblerox** [comment]
ok, i guess i fixed it.
