### ISSUE TITLE
What happened to flixel.addons.text.FlxBitmapFont?

### ISSUE THREAD

**Issue by greysondn** [HaxeFlixel/flixel-addons#282]
I've searched the history but I'm not so great at parsing for a single file. There didn't seem to be any notable issues or commits for it and I'm kinda' miffed.

So... where did it go? It seems to be poofed.

**Comment by Gama11** [comment]
This is the relevant commit: 7e135db

The mentioned `FlxBitmapTextField` is now `flixel.text.FlxBitmapText` ([Demo](http://haxeflixel.com/demos/FlxBitmapText/)).

**Comment by greysondn** [comment]
Thanks for the locate.
