### ISSUE TITLE
Help working with flipped objects on tiled

### ISSUE THREAD

**Issue by Tembac** [HaxeFlixel/flixel-addons#287]
Flixel version: 4.2.0
Flixel addons version: 2.2.0
OpenFL version: 3.6.1
Lime version: 2.9.1
_____

I'm working with tiled for the levels and I want to use the Flipping variable to know if an object is flipped. I'm not sure how it works because that variable seems to change the Gid of the object. 
I'm using the gid to know which object is each one but when I flip it changes.

For example, an object without flip can have a gid that is: 4372 and the same object flipped have the gid: 2147488019

On TiledObject.hx I have functions to know if an object is flipped but I want to also know the gid before the flip so I can know which object is. 

I'm not sure if this is something that I'm supposed to handle on my code or maybe there is something I'm missing.

This can be tested on the tiled demo: https://github.com/HaxeFlixel/flixel-demos/tree/dev/Editors/TiledEditor

**Comment by Tembac** [comment]
I actually found a bug with how this is done by HaxeFlixel. TiledObject.hx from Flixel addons:

               // object with tile association?
		if (source.has.gid && source.att.gid.length != 0) 
		{
			trace("gid lenght " + source.att.gid.length);
			gid = Std.parseInt(source.att.gid);
			
			for (set in layer.map.tilesets)
			{
				shared = set.getPropertiesByGid(gid);
				
				if (shared != null)
				{
					break;
				}
			}
			
			trace("shared " + shared);
			// If there is a gid it means that it's a tile object
			objectType = TILE;
		}

Here it sets the gid and takes the shared properties from the tileset. But if the tile object is flipped the shared properties are null.

**Comment by alihassan0** [comment]
I would like to investigate this as well since I am currently using flipped tiles too. 
so just to be clear .. you are saying that there is a problem with the GIDs themselves but the are rendered correctly or that there is a problem with rendering them too ?

**Comment by Tembac** [comment]
It depens on how you do to render the objects on screen. I'm using a code similar to the tiled demo so the rendering is also not working.

This is not for the tile layers but the object layer. I'm not sure about the tile layer.

**Comment by alihassan0** [comment]
[flippedTilesTest.zip](https://github.com/HaxeFlixel/flixel-addons/files/752052/flippedTilesTest.zip)
I just made a simple test and both fiipped/animated tiles and rotated objects are working properly .. 
can you elaborate on the GID problem ?

**Comment by Tembac** [comment]
Thanks but I'm talking about the flipping property of the objects on the object layer, not the tile layer:
http://puu.sh/tOm6X/97a6ee615b.png

**Comment by alihassan0** [comment]
Hmmm ... I understood you were talking about tiledObjects. in my example above I used `angle` to flip the tiles..

 but when I used the flipping properties .. it wasn't correctly parsed. So I think that this is probably a bug. 

I will try to inspect it more soon.

**Comment by Tembac** [comment]
I made the following changes to tiledObject.hx. It works for flash platform but not for windows platform :(

`package flixel.addons.editors.tiled;

import haxe.xml.Fast;
import flixel.math.FlxPoint;

/**
 * (original by Matt Tuttle based on Thomas Jahn's. Haxe port by Adrien Fischer)
 * This content is released under the MIT License.
 */
class TiledObject
{
	/**
	 * Use these to determine whether a sprite should be flipped, for example:
	 * 
	 * var flipped:Bool = (oject.gid & TiledObject.FLIPPED_HORIZONTALLY_FLAG) > 0;
	 * sprite.facing = flipped ? FlxObject.LEFT : FlxObject.RIGHT;
	 */
	public static inline var FLIPPED_VERTICALLY_FLAG = 0x40000000;
	public static inline var FLIPPED_HORIZONTALLY_FLAG = 0x80000000;
	public static inline var FLIPPED_DIAGONALLY_FLAG = 0x20000000;
	
	public static inline var RECTANGLE = 0;
	public static inline var ELLIPSE = 1;
	public static inline var POLYGON = 2;
	public static inline var POLYLINE = 3;
	public static inline var TILE = 4;
	
	public var x:Int;
	public var y:Int;
	public var width:Int;
	public var height:Int;
	public var name:String;
	public var type:String;
	public var xmlData:Fast;
	/** 
	 * In degrees
	 */
	public var angle:Float;
	/**
	 * Global identifier for this object
	 */
	public var gid:Int;
	/**
	 * Custom properties that users can set on this object
	 * If "type" is not defined, the parent layer's "defaultType" is used
	 */
	public var properties:TiledPropertySet;
	/** 
	 * Shared properties are tileset properties added on object tile
	 */ 
	public var shared:TiledPropertySet;
	/**
	 * Information on the layer that contains this object
	 */
	public var layer:TiledObjectLayer;
	/**
	 * The type of the object (RECTANGLE, ELLIPSE, POLYGON, POLYLINE, TILE)
	 */
	public var objectType(default, null):Int;
	/**
	 * Whether the object is flipped horizontally.
	 */
	public var flippedHorizontally:Bool;
	/**
	 * Whether the object is flipped vertically.
	 */
	public var flippedVertically:Bool;
	/**
	 * An array with points if the object is a POLYGON or POLYLINE
	 */
	public var points:Array<FlxPoint>;
	
	public function new(source:Fast, parent:TiledObjectLayer)
	{
		xmlData = source;
		layer = parent;
		name = (source.has.name) ? source.att.name : "";
		type = (source.has.type) ? source.att.type :
		        (parent.properties.contains("defaultType") ? parent.properties.get("defaultType") : "");
		x = Std.parseInt(source.att.x);
		y = Std.parseInt(source.att.y);
		width = (source.has.width) ? Std.parseInt(source.att.width) : 0;
		height = (source.has.height) ? Std.parseInt(source.att.height) : 0;
		angle = (source.has.rotation) ? Std.parseFloat(source.att.rotation) : 0;
		// By default let's it be a rectangle object
		objectType = RECTANGLE;
		
		// resolve inheritence
		shared = null;
		gid = -1;
		
		// object with tile association?
		if (source.has.gid && source.att.gid.length != 0) 
		{
			gid = Std.parseInt(source.att.gid);
			
			flippedHorizontally = (gid & FLIPPED_HORIZONTALLY_FLAG) < 0;
			
			flippedVertically = (gid & FLIPPED_VERTICALLY_FLAG) > 0;
			
			gid &= ~(FLIPPED_HORIZONTALLY_FLAG |
                        FLIPPED_VERTICALLY_FLAG );
						
			for (set in layer.map.tilesets)
			{
				shared = set.getPropertiesByGid(gid);
				
				if (shared != null)
				{
					break;
				}
			}
			// If there is a gid it means that it's a tile object
			objectType = TILE;
		}
		
		// load properties
		properties = new TiledPropertySet();
		
		for (node in source.nodes.properties)
		{
			properties.extend(node);
		}
		
		// Let's see if it's another object
		if (source.hasNode.ellipse)
		{
			objectType = ELLIPSE;
		}
		else if (source.hasNode.polygon)
		{
			objectType = POLYGON;
			getPoints(source.node.polygon);
		}
		else if (source.hasNode.polyline)
		{
			objectType = POLYLINE;
			getPoints(source.node.polyline);
		}
	}
	
	private function getPoints(node:Fast):Void
	{
		points = new Array<FlxPoint>();
		
		var pointsStr:Array<String> = node.att.points.split(" ");
		var pair:Array<String>;
		for (p in pointsStr)
		{
			pair = p.split(",");
			points.push(FlxPoint.get(Std.parseFloat(pair[0]), Std.parseFloat(pair[1])));
		}
	}
}
`
