### ISSUE TITLE
TiledObject: fix Haxe 3.2 compatibility

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel-addons#290]
See https://github.com/HaxeFlixel/flixel-addons/pull/288#issuecomment-278168113

**Comment by MSGhero** [comment]
I'm on mobile, but did Int64Helper's parse string exist back then? I've used it but idr the Haxe version.

**Comment by Gama11** [comment]
No, that's the problem. The only solution might be to include that in `TiledObject`...
