### ISSUE TITLE
_bounds never recalculated to allow for position changed in FlxSlider

### ISSUE THREAD

**Issue by Skerper** [HaxeFlixel/flixel-addons#306]
More or less what it says. _bounds is calculated in FlxSlider.createSlider(), and then never seems to be touched again.

If you change the position of the slider via its x/y values, the _bounds remains the same, which causes FlxMath.mouseInFlxRect(false, _bounds) in FlxSlider.update() to be ineffective (slider is only able to be activated/manipulated when the mouse is in the area where it used to be).

Not sure if this is best solved recalculating _bounds each update, offering a recalculateBounds() public method which the user must call manually, having a setPosition(x,y) public method, or doing some setter fuckery with the x/y properties.

Unsurprisingly this also breaks FlxUISlider in flixel-ui.

**Comment by JoeCreates** [comment]
Considering it is very cheap to modify the bounds it should probably be
done in the setters.
