### ISSUE TITLE
Add multiplayer support

### ISSUE THREAD

**Issue by steverichey** [HaxeFlixel/flixel-addons#31]
Would probably use [Haxe remoting](http://haxe.org/doc/remoting) unless OpenFL has some functionality that would make this easier. Could be a dedicated class like `FlxMultiplayer` or something, but would probably need both server and client code.

**Comment by AndreiRegiani** [comment]
Nuggeta seems to be the best solution as backend: http://www.nuggeta.com

* It has official support for Haxe/OpenFL, demo included.

* Nuggeta is completely free to use, you just need to provide your own hosting, there is a one click deploy for Google Cloud Platform which is very affordable.

* Multiplatform: Win/Mac/Linux


Would be a nice to see a wrapper of this for HaxeFlixel. 
If anyone is interested, let's discuss here how it should be implemented.

I wonder if something like this for the client-side is possible:

* FlxMultiplayerState, there a method ``onMessage()`` to receive custom messages/actions.

* FlxMultiplayerSprite, this will automatically send its fields (position, rotation, more) to the server.

So with only this you already have synchronized world between connections.

**Comment by mobsterSquirrel** [comment]
I've been interested in online multiplayer implementation, but I know nothing, I mean ZERO about it. I'm willing to learn, and eventually teach...

**Comment by Gama11** [comment]
This issue has been stale for a while now, so I'll go ahead and close it. Also, by now there's mphx, which seems to have a nice Flixel example, so I'm not sure we really need anything in flixel-addons:

https://github.com/5Mixer/mphx
