### ISSUE TITLE
[Feature] Add Support for Tiled Collision Editor

### ISSUE THREAD

**Issue by zicklag** [HaxeFlixel/flixel-addons#316]
The Tiled editor has a collision editor that can be used to add collision shapes to tiles on a tilemap. It would be great if the Tiled Flixel addon would support loading those collision shapes from the tile. It should be easy to add the data to the [`TiledTilePropertySet`](https://api.haxeflixel.com/flixel/addons/editors/tiled/TiledTilePropertySet.html). Even if was as simple as loading the XML data into a `Fast` like is already done by the [`TiledObject`](https://api.haxeflixel.com/flixel/addons/editors/tiled/TiledObject.html) class, I think it would still be useful.

**Comment by Gama11** [comment]
Pull request? :)
