### ISSUE TITLE
[Feature] Add support for tiled grouped layers

### ISSUE THREAD

**Issue by guifes** [HaxeFlixel/flixel-addons#319]
That's about it

**Comment by Gama11** [comment]
I'm not very familiar with the details of Tiled's map format, got any more details about this? Or are you working on a PR anyway? :)

**Comment by guifes** [comment]
I have created a PR https://github.com/HaxeFlixel/flixel-addons/issues/319.

I made it trying to change as little as I could from the original code base. Tiled kinda treats groups as layers so I created a TiledGroupLayer, added another type to TiledLayers Type named GROUP, and when loading layers I check for group layer and add all it's internal layers recursively. I forwarded the noLoadHash to TiledGroupLayer so that it could check for "no load layers" as well.
