### ISSUE TITLE
FlxMouseControl error when compile in android

### ISSUE THREAD

**Issue by BlazeDrako** [HaxeFlixel/flixel-addons#325]
Hello, i have this error when i run the game in android, in another build it run perfectly
```
source/MenuItem.hx:38: characters 23-38 : Unknown identifier : FlxMouseControl
source/MenuItem.hx:38: characters 23-38 : For function argument 'ClassType'
```
i use the next command to launch it
```
run lime build "Project.xml" android -debug -Dfdb
```
i use HaxeDevelop programm.

how can i solve this error?

**Comment by Gama11** [comment]
`FlxMouseControl` is only available if `FLX_MOUSE` is defined:

https://github.com/HaxeFlixel/flixel-addons/blob/dev/flixel/addons/plugin/FlxMouseControl.hx#L3

By default, this is not the case on mobile due to this line in `Project.xml` files:

```xml
<haxedef name="FLX_NO_MOUSE" if="mobile" />
```

Should work if you comment that out.

**Comment by BlazeDrako** [comment]
Thanks, it works.
