### ISSUE TITLE
FlxSliceSprite doesn't work on native

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel-addons#328]
We see just one mis-scaled corner.

haxeflixel dev, openfl 8.7, lime 7.2

```add(new FlxSliceSprite(new openfl.display.BitmapData(24, 24), FlxRect.get(8, 8, 16, 12), 100, 50));```

**Comment by JoeCreates** [comment]
How's that? Observed, we see a tiny white square whereas we should see the 100x50 box which correctly shows on flash.

**Comment by Gama11** [comment]
This is what it looks like with OpenFL 3.6.1 / Lime 2.9.1:

![](https://i.imgur.com/0ziOW2G.png)

**Comment by Tembac** [comment]
I'm having similar problems.

Flash:
![image](https://user-images.githubusercontent.com/2808285/50705336-42b74c80-1039-11e9-99d3-1cc524cde280.png)

Windows cpp:
![image](https://user-images.githubusercontent.com/2808285/50705347-52369580-1039-11e9-9497-66786d6e5dd7.png)

Code:

`		var container:FlxSliceSprite = new FlxSliceSprite("assets/images/panel.png", new FlxRect(32, 32, 96, 96), 416, 416);
		container.setPosition(64, 39);
		add(container);`

Image panel:
![panel](https://user-images.githubusercontent.com/2808285/50705383-69758300-1039-11e9-9d93-f745e6b3385e.png)

**Comment by JoeCreates** [comment]
This is now fixed by a recent openfl commit.
