### ISSUE TITLE
FlxBackdrop possible hitbox overlook?

### ISSUE THREAD

**Issue by EyeDaleHim** [HaxeFlixel/flixel-addons#380]
![image](https://user-images.githubusercontent.com/71162374/229362469-95a0543e-8d2f-40db-af33-43debd529687.png)

Using `FlxBackdrop`, it seems to be that the original sprite only gets the hitbox, but this isn't the case for the copied ones?

**Comment by Geokureli** [comment]
Correct, FlxBackdrops we're created for graphical purposes, rather than collision purposes.

How would collision even work? It's meant to be infinitely sized

**Comment by EyeDaleHim** [comment]
Very understandable, I will find another method without using FlxBackdrops, tee hee.
