### ISSUE TITLE
tilemap doesn't render specific tiles

### ISSUE THREAD

**Issue by poisonHornGames** [HaxeFlixel/flixel-addons#420]
the tilemap doesn't render the 1st tile of the set

ingame screenshot:
![Screenshot_20240107_133929](https://github.com/HaxeFlixel/flixel-addons/assets/155884736/8f5a983f-c1a3-4a31-bee7-5830306f4455)

screenshot in ogmo editor:
![Screenshot_20240107_134340](https://github.com/HaxeFlixel/flixel-addons/assets/155884736/ff1f4c4d-4b51-4ec1-add3-66d11e8b1416)

![code](https://github.com/HaxeFlixel/flixel-addons/assets/155884736/ac9aca13-82c7-44a2-bd64-dbaa6afe1aeb)

**Comment by Geokureli** [comment]
I recommend having an empty tile in the first spot, ogmo uses -1 for empty space but flixel changes all negative tiles to 0 and typically uses 0 for empty tiles
