### ISSUE TITLE
FlxRuntimeShader tween function

### ISSUE THREAD

**Issue by Vortex2Oblivion** [HaxeFlixel/flixel-addons#428]
I think it would be a good idea to add a way to tween FlxRuntimeShader values. I was able to implement this myself with a simple FlxTween.num function, but it seems like something that should be in the base flixel-addons repo.

**Comment by Geokureli** [comment]
was there an issue with using FlxTween.num? this seems like 1 or 2 lines of code

**Comment by Vortex2Oblivion** [comment]
Not really.

**Comment by Vortex2Oblivion** [comment]
How is it hyper specific

**Comment by Geokureli** [comment]
because it's a tween function specifically for a shader value, when we already have a generalized tween tool
