### ISSUE TITLE
FlxPieDial black border

### ISSUE THREAD

**Issue by Mystically11** [HaxeFlixel/flixel-addons#430]
Upon creating a FlxPieDial, it renders with a black border around it. That border disappears as the pie empties out. In the HaxeFlixel demo of it, the background is black itself, so it's not noticeable. Might have been an uncaught bug or something breaking as time passed on.

example:
![image](https://github.com/HaxeFlixel/flixel-addons/assets/100186990/65fdb66a-417b-40d7-866e-a0fd9c4de9a5)

**Comment by Geokureli** [comment]
This is fixed and should be released soon, I also added FlxRadialGauge which I recommend using instead of FlxPieDial

**Comment by Geokureli** [comment]
um thanks for asking me to fix this, it's popping off on twitter right now

<img width="598" alt="Screenshot 2024-10-01 at 3 33 01 PM" src="https://github.com/user-attachments/assets/d01cbab8-529e-4564-9970-f20c6f3d2772">

Anything else you need?

**Comment by Vortex2Oblivion** [comment]
> Anything else you need?

Add support for 5d objects petty please

**Comment by Geokureli** [comment]
k

**Comment by Geokureli** [comment]
> > Anything else you need?
> 
> Add support for 5d objects petty please

technically, any multi-slot save system is technically 5-dimensions when you think of 5d as consisting of 3 spacial dimensions and 2 temporal dimensions. So I'm gonna mark this as resolved
