### ISSUE TITLE
TiledMap support external tilesets

### ISSUE THREAD

**Issue by fzzr-** [HaxeFlixel/flixel-addons#76]
Need support to load external `tsx`-files linked to `tmx`-files. Maybe like assets loading.

E.g.: [perspective_walls.tmx](https://github.com/bjorn/tiled/blob/master/examples/perspective_walls.tmx#L3)

``` xml
<tileset firstgid="1" source="perspective_walls.tsx"/>
```
- Have no `name` attr
- Have a `source` attr

This rules means that we need to load a `tsx` from a directory that contains the our `tmx`.

If `tsx` isn't exist  then we need call something like this:
`loadExternalTileset(filename, success:String->Void)`.

**Comment by karliss** [comment]
After cd1ad4adb1f24803ad44570e36844b7d973fc5c0 seems to be working good enough as long as you specify correct rootPath.

**Comment by Gama11** [comment]
This is probably resolved by #312.
