### ISSUE TITLE
Rename package flixel.addons.editors to flixel.addons.format(s)

### ISSUE THREAD

**Issue by fzzr-** [HaxeFlixel/flixel-addons#78]
Need to rename the package `flixel.addons.editors` to `flixel.addons.format` because:
- We don't need dependence on vendors;
- We did not implement functionality of specific editors;
- Several editors can work with different formats;
- **We should support formats** like `tmx` instead concrete editors.

**Comment by Gama11** [comment]
I can see where you're coming from, but this would be a breaking change, which I'm not willing to make just for aesthetic purposes.

**Comment by fzzr-** [comment]
Three years. Okay :)
